### ISSUE TITLE
how i do to include subdirs?

### ISSUE THREAD

**Issue by alexlovar** [cluemediator/delete-files-from-folder-php#1]
hi, is a great sample, i have a question, how i do to include subdirs to clean all files too?

**Comment by cluemediator** [comment]
Hey Alexlovar,
We glad you like it.

It's an add on in the functionality to delete files from the subdirectories that we will cover in the upcoming article.

Please keep in touch.
Subscribe us for weekly updates or like and follow us for regular updates.

**Website:** https://www.cluemediator.com
**Facebook:** https://www.facebook.com/thecluemediator
**Twitter:** https://twitter.com/cluemediator

**Comment by cluemediator** [comment]
Check out [this article](https://www.cluemediator.com/remove-all-files-and-subfolders-from-a-folder-in-php).
